import {createState,reduce,presets,phases} from './model.mjs';
let state=createState(),toastTimer,lastTick=Date.now();const $=s=>document.querySelector(s),main=$('#main'),dialog=$('#dialog');
const titles={home:'游戏大厅',setup:'创建房间',lobby:'手环入座',check:'开局检查',play:'对局主持',done:'演示结束'};
const steps=()=>`<div class="steps" aria-label="准备进度">${['选择配置','手环入座','开局检查','开始对局'].map((x,i)=>`<span class="step ${['setup','lobby','check','play'][i]===state.view?'current':''}">${i+1}. ${x}</span>`).join('')}</div>`;
const intro=(tag,title,text)=>`<div class="page-intro"><div><div class="kicker">${tag}</div><h1>${title}</h1><p>${text}</p></div></div>`;
const button=(text,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const roleItems=()=>{const r=presets[state.count];return [['狼人',r.wolves],['预言家',r.seer],['女巫',r.witch],['村民',r.villagers]].filter(x=>x[1]).map(x=>`<div class="role-item"><span>${x[0]}</span><strong>× ${x[1]}</strong></div>`).join('');};
function render(){
 $('#top-title').textContent=titles[state.view];
 const s=state;
 if(s.view==='home')main.innerHTML=intro('LET’S PLAY','选择今晚的游戏','把主持交给主机，把推理留给彼此。')+`<div class="home-grid"><section class="game-feature"><span class="chip">首款交互演示 · 隐藏身份</span><div class="game-word">狼人杀</div><p>私密身份、夜间行动、白天讨论。<br>每个人都能加入这场推理。</p><div class="feature-bottom"><div class="metadata">6 / 9 / 12 人配置预览<br>主机 + 个人触屏手环</div>${button('创建房间 ↗','configure')}</div></section><section class="panel"><div class="kicker">QUICK START</div><h2 style="margin-top:16px">一桌人，三步开局</h2><ol class="how-list"><li><div>选好人数与配置<small>主机安排整场流程。</small></div></li><li><div>手环碰一下，入座<small>同一桌再来一局，无需重复绑定。</small></div></li><li><div>在手环查看私密身份<small>公共屏只显示公开信息。</small></div></li></ol></section></div><div class="section-title"><h2>后续游戏接口</h2><span>以下仅展示扩展方向，尚未接入</span></div><div class="upcoming-grid"><div class="upcoming"><div><h3>阿瓦隆</h3><p>阵营推理 · 团队决策</p></div><span class="subtle-tag">待接入</span></div><div class="upcoming"><div><h3>谁是卧底</h3><p>私密词语 · 发言投票</p></div><span class="subtle-tag">待接入</span></div></div>`;
 if(s.view==='setup')main.innerHTML=steps()+intro('ROOM SETUP','先为这一桌做好准备','配置只展示角色数量，不显示任何玩家的身份。')+`<div class="two-col"><section class="panel"><h2>狼人杀</h2><p class="muted">第一版 · 公共触屏流程预览</p><span class="field-label">这一桌有几个人？</span><div class="segmented" role="group" aria-label="玩家人数">${[6,9,12].map(n=>button(`${n} 人`,'count',`choice ${s.count===n?'selected':''}`,`data-value="${n}" aria-pressed="${s.count===n}"`)).join('')}</div><span class="field-label">白天讨论计时</span><div class="segmented" role="group" aria-label="讨论时长">${[120,180,300].map(n=>button(`${n/60} 分钟`,'duration',`choice ${s.duration===n?'selected':''}`,`data-value="${n}" aria-pressed="${s.duration===n}"`)).join('')}</div><div class="notice">这是界面演示配置，不代表已经验证的平衡阵容。正式开局前还需确定完整规则版本和角色技能。</div></section><section class="panel"><div class="kicker">TABLE OVERVIEW</div><h2 style="margin-top:15px">本桌配置</h2><div class="role-list">${roleItems()}</div><div class="summary-line"><span>玩家手环</span><strong>${s.count} 只</strong></div><div class="summary-line"><span>建议网关（待实测）</span><strong>${Math.ceil(s.count/6)} 个</strong></div><div class="summary-line"><span>身份查看位置</span><strong>个人手环</strong></div><p class="scroll-note">不接硬件也可以完成本次界面体验。</p></section></div><div class="actions">${button('返回大厅','home','secondary')}${button('下一步 · 手环入座 →','lobby')}</div>`;
 if(s.view==='lobby')main.innerHTML=steps()+intro('TAKE A SEAT','戴好手环，找到你的座位','正式使用时，将手环靠近主机 NFC 区完成首次绑定。')+`<div class="two-col"><section class="panel"><div class="section-title" style="margin-top:0"><h2>座位与手环</h2><span>点击座位模拟入座</span></div><div class="seats">${Array.from({length:s.count},(_,i)=>i+1).map(n=>`<button class="seat ${s.bound.includes(n)?'connected':''}" data-action="seat" data-value="${n}" aria-label="${n}号座位，${s.bound.includes(n)?'已模拟连接，点击管理':'点击模拟绑定'}"><strong>${String(n).padStart(2,'0')}</strong><span>${s.bound.includes(n)?'演示已连接':'等待手环'}</span></button>`).join('')}</div><p class="muted" style="font-size:14px">公共屏仅显示座位和设备状态，不显示角色。</p></section><section class="panel"><span class="chip">模拟连接</span><div class="big-count">${s.bound.length} <small>/ ${s.count} 人已入座</small></div><div class="progress"><i style="width:${s.bound.length/s.count*100}%"></i></div><div class="tap-hint"><strong>本次不用真的刷卡</strong><p class="muted">点击左侧空座位，或者一键模拟全部入座，体验后续流程。</p>${button('模拟全部入座','bindAll','secondary full',s.bound.length===s.count?'disabled':'')}</div><p class="scroll-note">未读取真实设备、电量或信号。</p></section></div><div class="actions">${button('上一步','backSetup','secondary')}${button('入座完成 · 开局检查 →','check','primary',s.bound.length!==s.count?'disabled':'')}</div>`;
 if(s.view==='check')main.innerHTML=steps()+intro('READY CHECK','最后检查，然后开始','这块屏幕只负责公共流程，不展示或播报秘密身份。')+`<div class="two-col"><section class="panel"><h2>本局准备</h2><div class="check-row"><span class="mark">✓</span><div>${s.count} 个座位已模拟入座<small>正式接入后还需检查连接、电量和个人确认。</small></div></div><div class="check-row"><span class="mark">✓</span><div>公共屏隐私模式<small>不包含座位对应身份，也不显示夜间行动者。</small></div></div><div class="check-row"><span class="mark">♪</span><div>试播公共主持词<small>使用浏览器语音，是否有中文音色取决于设备。</small></div>${button('试播','sound','secondary')}</div><label class="check-row"><input type="checkbox" id="ack" ${s.ack?'checked':''}><div>我知道这是交互演示<small>没有真实发牌、硬件连接、行动收集和胜负结算。</small></div></label></section><section class="panel"><div class="kicker">YOUR TABLE</div><h2 style="margin-top:16px">狼人杀 · ${s.count} 人</h2><div class="summary-line"><span>讨论时间</span><strong>${s.duration/60} 分钟</strong></div><div class="summary-line"><span>流程</span><strong>夜间 → 讨论 → 投票</strong></div><div class="privacy-note">身份在手环上私密查看。<br>本页不会以“调试”为由公开全体身份。</div></section></div><div class="actions">${button('返回座位','lobby','secondary')}${button('开始主持演示 →','start','primary',s.ack?'':'disabled')}</div>`;
 if(s.view==='play'){const ph=phases[s.phase];main.innerHTML=intro('LIVE TABLE · DEMO',`狼人杀 · 第 ${s.round} 轮`,'本地流程演示，操作不会发送到任何真实手环。')+`<div class="play-layout"><section class="stage ${s.phase===1?'day':''}"><span class="chip">${s.paused?'已暂停':ph.name}</span><h2 class="stage-name">${ph.title}</h2><div class="timer" id="timer" aria-label="阶段剩余时间">${time(s.remaining)}</div><div class="host-script"><span>公共主持词</span>${ph.script}</div><div class="stage-buttons">${button(s.paused?'继续计时':'暂停计时','pause','secondary',s.phase===3?'disabled':'')}${button('播放主持词','narrate','secondary')}</div></section><section class="panel"><h2>本轮流程</h2><ol class="timeline">${phases.map((x,i)=>`<li class="${s.phase===i?'current':''}"><span>${String(i+1).padStart(2,'0')}　${x.name}</span><span>${i<s.phase?'已展示':i===s.phase?'当前':'待进行'}</span></li>`).join('')}</ol><h3 style="margin-top:26px">本桌座位</h3><div class="connection-grid">${s.bound.map(n=>`<span>${String(n).padStart(2,'0')}</span>`).join('')}</div><p class="scroll-note">仅为模拟绑定状态。夜间不公开个人行动与提交进度。</p><div class="notice">这里的“下一阶段”仅用于演示。正式游戏必须由规则服务确认后推进。</div>${button(s.phase===3?'完成演示':'演示 · 下一阶段 →',s.phase===3?'finish':'next','primary full',s.paused&&s.phase!==3?'disabled':'')}</section></div><div class="actions">${button('结束本次演示','exit','quiet-button')}<span class="muted" id="timer-note">${s.remaining===0?'计时结束，请手动继续演示。':'计时归零不会自动判定玩家行动。'}</span></div>`;}
 if(s.view==='done')main.innerHTML=`<section class="panel end-panel"><div class="kicker">SEE YOU NEXT ROUND</div><span class="chip">流程预览结束</span><h1>下一局，不用重新入座。</h1><p class="muted">手环与座位绑定可以复用。正式游戏会重新分配身份；<br>这次演示未产生真实角色、投票或胜负。</p><div class="summary-line"><span>已模拟绑定</span><strong>${s.bound.length} 只手环</strong></div><div class="summary-line"><span>已体验</span><strong>准备 / 入座 / 主持流程</strong></div><div class="actions">${button('返回游戏大厅','home','secondary')}${button('保留座位 · 再来一局','again')}</div></section>`;
}
function time(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function dispatch(type,extra={}){const previous=state.view;state=reduce(state,{type,...extra});if(type!=='tick'){lastTick=Date.now();render();if(previous!==state.view){window.scrollTo(0,0);main.focus({preventScroll:true});}}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function modal(title,body,actions=''){dialog.innerHTML=`<div class="dialog-header"><h2 id="dialog-title">${title}</h2>${button('×','close','icon-button','aria-label="关闭弹窗"')}</div>${body}${actions?`<div class="dialog-actions">${actions}</div>`:''}`;dialog.showModal();}
function say(text){if(!('speechSynthesis'in window)){toast('当前浏览器不支持播音，请阅读屏幕主持词。');return;}window.speechSynthesis.cancel();const msg=new SpeechSynthesisUtterance(text);msg.lang='zh-CN';msg.volume=state.volume;msg.rate=.92;msg.onerror=()=>toast('播音不可用，请检查系统中文语音或阅读屏幕文字。');window.speechSynthesis.speak(msg);toast('已请求播放公共主持词');}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action,value=Number(b.dataset.value);
 if(action==='close'){dialog.close();return;}
 if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('此浏览器不支持全屏，请使用横屏浏览。');}catch{toast('无法切换全屏，请使用横屏浏览。');}return;}
 if(action==='help'){modal('怎样体验这块主机屏幕',`<ol class="how-list"><li><div>创建狼人杀房间<small>选择人数与讨论时间。</small></div></li><li><div>模拟手环入座<small>点击空座位或一键模拟，不需要 NFC。</small></div></li><li><div>开始主持演示<small>体验计时、播音、暂停和阶段切换。</small></div></li></ol><div class="notice">本版只实现主机公共页面。手环界面、真实发牌和规则结算另行开发。刷新页面会重置演示。</div>`);return;}
 if(action==='devices'){modal('设备连接',`<p>尚未接入真实硬件。</p><div class="summary-line"><span>NFC 读写器</span><strong>未连接</strong></div><div class="summary-line"><span>蓝牙网关</span><strong>未连接</strong></div><div class="summary-line"><span>演示座位</span><strong>${state.bound.length} / ${state.count}</strong></div><p class="scroll-note">模拟入座不会验证蓝牙信号或电池电量。正式版将通过主机服务接入设备事件。</p>`);return;}
 if(action==='settings'){modal('设置与音频',`<label for="volume" class="field-label">播音音量 <span id="volume-value">${Math.round(state.volume*100)}%</span></label><input id="volume" type="range" min="0" max="100" value="${state.volume*100}">${button('试播公共主持词','sound','secondary full')}<p class="scroll-note">使用设备自带语音。请确认系统音量已打开；正式版优先采用本地预录主持词。</p>`);return;}
 if(action==='sound'){say('欢迎来到桌游主持台。请在自己的手环上查看身份，公共屏只显示公开信息。');return;}
 if(action==='narrate'){say(phases[state.phase].script);return;}
 if(action==='seat'){if(state.bound.includes(value)){modal(`${value} 号座位`, '<p>这只手环已模拟连接。更换玩家时可以解除绑定，再重新入座。</p>',button('取消','close','secondary')+button('解除模拟绑定','unbind','danger',`data-value="${value}"`));}else{dispatch('bind',{seat:value});toast(`${value} 号座位已模拟入座`);}return;}
 if(action==='unbind'){dialog.close();dispatch('unbind',{seat:value});return;}
 if(action==='exit'){modal('结束本次演示？','<p>退出主持流程，保留座位绑定。这里没有真实对局，不会产生胜负结果。</p>',button('继续体验','close','secondary')+button('结束演示','confirmExit','danger'));return;}
 if(action==='confirmExit'){dialog.close();window.speechSynthesis?.cancel();dispatch('finish');return;}
 if(action==='home'&&state.view!=='home'){modal('返回游戏大厅？','<p>本次演示的配置与模拟绑定将清空。</p>',button('留在此页','close','secondary')+button('返回大厅','confirmHome','danger'));return;}
 if(action==='confirmHome'){dialog.close();window.speechSynthesis?.cancel();dispatch('home');return;}
 if(['next','pause','finish','again'].includes(action))window.speechSynthesis?.cancel();
 dispatch(action,{value});
});
document.addEventListener('change',e=>{if(e.target.id==='ack')dispatch('ack',{value:e.target.checked});});
document.addEventListener('input',e=>{if(e.target.id==='volume'){state=reduce(state,{type:'volume',value:Number(e.target.value)/100});$('#volume-value').textContent=`${Math.round(state.volume*100)}%`;}});
setInterval(()=>{const now=Date.now(),elapsed=Math.floor((now-lastTick)/1000);if(elapsed<1)return;lastTick+=elapsed*1000;if(state.view!=='play'||state.paused)return;const ticks=Math.min(elapsed,state.remaining);for(let i=0;i<ticks;i++)state=reduce(state,{type:'tick'});if($('#timer'))$('#timer').textContent=time(state.remaining);if($('#timer-note')&&state.remaining===0)$('#timer-note').textContent='计时结束，请手动继续演示。';},250);
render();
// Optional page tools. Unsupported browsers keep the same touch experience.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const report=()=>({mode:'demo',view:state.view,playerCount:state.count,boundSeats:[...state.bound],phase:state.view==='play'?phases[state.phase].name:null});
 const empty={type:'object',properties:{},additionalProperties:false};
 const validate=input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');};
 const tools=[{name:'read_public_demo_state',title:'读取主持演示状态',description:'只读取公共演示状态，不包含秘密身份或真实设备信息。',inputSchema:empty,annotations:{readOnlyHint:true},execute(input){validate(input);return report();}},
 {name:'start_room_configuration',title:'打开房间配置',description:'从游戏大厅打开狼人杀配置页，不开始对局、不连接设备。仅在大厅可用。',inputSchema:empty,annotations:{readOnlyHint:false},execute(input){validate(input);if(state.view!=='home')throw new Error('请先通过页面确认返回大厅');dispatch('configure');return report();}}];
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
