import assert from 'node:assert/strict';
import {createState,reduce,presets} from './model.mjs';
let s=createState();
assert.equal(reduce(s,{type:'start'}),s);
s=reduce(s,{type:'configure'});
for(const n of [6,9,12])assert.equal(Object.values(presets[n]).reduce((a,b)=>a+b,0),n);
s=reduce(s,{type:'count',value:12});s=reduce(s,{type:'lobby'});
assert.equal(reduce(s,{type:'check'}),s);
assert.equal(reduce(s,{type:'bind',seat:13}),s);
s=reduce(s,{type:'bind',seat:1});s=reduce(s,{type:'bind',seat:1});assert.equal(s.bound.length,1);
s=reduce(s,{type:'bindAll'});assert.equal(s.bound.length,12);
s=reduce(s,{type:'unbind',seat:1});assert.equal(s.bound.length,11);
s=reduce(s,{type:'bind',seat:1});s=reduce(s,{type:'check'});
assert.equal(reduce(s,{type:'start'}),s);
s=reduce(s,{type:'ack',value:true});s=reduce(s,{type:'start'});assert.equal(s.view,'play');
s=reduce(s,{type:'pause'});assert.equal(reduce(s,{type:'tick'}),s);assert.equal(reduce(s,{type:'next'}),s);
s=reduce(s,{type:'pause'});for(let i=0;i<90;i++)s=reduce(s,{type:'tick'});assert.equal(s.remaining,0);assert.equal(s.phase,0);
s=reduce(s,{type:'next'});assert.equal(s.remaining,180);
s=reduce(s,{type:'next'});s=reduce(s,{type:'next'});assert.equal(s.phase,3);
s=reduce(s,{type:'finish'});assert.equal(s.view,'done');
s=reduce(s,{type:'again'});assert.equal(s.bound.length,12);assert.equal(s.ack,false);assert.equal(s.view,'check');
s=reduce(s,{type:'home'});assert.equal(s.bound.length,0);
for(const forbidden of ['roles','identity','votes','privateView'])assert.equal(forbidden in s,false);
console.log('PASS: setup, player counts, binding, guards, pause, timer, phases, reuse, reset, public-state boundary');
